[pyprland]
plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm"
class = "alacritty-dropterm"
lazy = true
size = "42% 46%"

[scratchpads.notes]
animation = "fromRight"
command = "feathernotes"
class = "feathernotes"
lazy = true
margin = 5
size = "40% 50%"

[scratchpads.passw]
animation = "fromTop"
command = "keepassxc"
class = "org.keepassxc.KeePassXC"
lazy = true
size = "60% 60%"

[scratchpads.rang]
animation = "fromTop"
command = "alacritty --class=ranger -e sudo -E ranger"
class = "ranger"
lazy = true
