# Shell variables
# Generated by 'wal'
wallpaper='/home/thor/.wallpapers/0057.jpg'

# Special
background='#0E1716'
foreground='#afbbe5'
cursor='#afbbe5'

# Colors
color0='#0E1716'
color1='#284B91'
color2='#2A509B'
color3='#3057A9'
color4='#4F67AF'
color5='#5473C9'
color6='#8A739D'
color7='#afbbe5'
color8='#7a82a0'
color9='#284B91'
color10='#2A509B'
color11='#3057A9'
color12='#4F67AF'
color13='#5473C9'
color14='#8A739D'
color15='#afbbe5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
