--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/thor/.wallpapers/0057.jpg"

-- Special
background="#0E1716"
foreground="#afbbe5"
cursor="#afbbe5"

-- Colors
color0="#0E1716"
color1="#284B91"
color2="#2A509B"
color3="#3057A9"
color4="#4F67AF"
color5="#5473C9"
color6="#8A739D"
color7="#afbbe5"
color8="#7a82a0"
color9="#284B91"
color10="#2A509B"
color11="#3057A9"
color12="#4F67AF"
color13="#5473C9"
color14="#8A739D"
color15="#afbbe5"
